In [1]:
%reload_ext autoreload
%autoreload 2

import sys
sys.path.append("..")

import numpy as np
import healpy as hp

import jax.numpy as jnp

In [2]:
from models.np_model_gc import NPModelGC17
from models.scd import dnds
from likelihoods.npll_jax import log_like_np
from likelihoods.npll_jax_new import log_like_np as log_like_np_new

/n/home07/yitians/.conda/envs/torch/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [19]:
wdir = "/n/home07/yitians/fermi/fermi-prob-prog/production"
mask_norm = jnp.load(f"{wdir}/mask_norm.npy")

data_dir = "../outputs/simulations"
data = np.load(f"{data_dir}/sim_gc17_deltapsf_n100.npy")[0]
data_full = np.zeros(hp.nside2npix(128))
data_full[~mask_norm] = data
data_in = jnp.array(data_full, dtype=jnp.int32)

m = NPModelGC17(psf_tags=['delta', 'analytic'])

Number of pixels in ROI: 6839
Using PSF tags: ['delta', 'analytic']
Calculating the psf correction ...
Max photon count is 103


# 3. Fix final bin as well

In [20]:
m.f_ary

array([0.00000000e+00, 2.82079442e-05, 1.30929679e-04, 6.07721735e-04,
       2.82079442e-03, 1.30929679e-02, 6.07721735e-02, 1.19565217e-01,
       1.58695652e-01, 1.97826087e-01, 2.36956522e-01, 2.76086956e-01,
       3.15217391e-01, 3.54347826e-01, 3.93478261e-01, 4.32608695e-01,
       4.71739130e-01, 5.10869565e-01, 5.50000000e-01, 5.89130434e-01,
       6.28260869e-01, 6.67391304e-01, 7.06521738e-01, 7.45652173e-01,
       7.84782608e-01, 8.23913043e-01, 8.63043477e-01, 9.02173912e-01,
       9.41304347e-01, 9.80434782e-01, 1.00000000e+00])

In [21]:
m.df_rho_ary

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [15]:
np.dot(m.f_ary, m.df_rho_ary)

1.0

In [ ]:
# before
ll_new()

m.df_rho_ary[0] 123.0


Array([-2.34757305, -2.1989154 , -2.35438931, ..., -2.20243678,
       -2.21588883, -2.47552885], dtype=float64)

In [22]:
# after
ll_new()

m.df_rho_ary[0] 0.0
m.df_rho_ary[-1] 1.0


Array([-2.34558046, -2.19808685, -2.35449374, ..., -2.20053063,
       -2.2139745 , -2.47638205], dtype=float64)

# 2. independence of zeroth bin

In [22]:
# previous f
m.f_ary

array([5.00000000e-06, 2.82079442e-05, 1.30929679e-04, 6.07721735e-04,
       2.82079442e-03, 1.30929679e-02, 6.07721735e-02, 1.19565217e-01,
       1.58695652e-01, 1.97826087e-01, 2.36956522e-01, 2.76086957e-01,
       3.15217391e-01, 3.54347826e-01, 3.93478261e-01, 4.32608696e-01,
       4.71739130e-01, 5.10869565e-01, 5.50000000e-01, 5.89130435e-01,
       6.28260870e-01, 6.67391304e-01, 7.06521739e-01, 7.45652174e-01,
       7.84782609e-01, 8.23913043e-01, 8.63043478e-01, 9.02173913e-01,
       9.41304348e-01, 9.80434783e-01])

In [23]:
m = NPModelGC17(psf_tags=['delta'])

Number of pixels in ROI: 6839
Using PSF tags: ['delta']
Calculating the psf correction ...
Max photon count is 103


In [24]:
m.f_ary

array([0.00000000e+00, 2.82079442e-05, 1.30929679e-04, 6.07721735e-04,
       2.82079442e-03, 1.30929679e-02, 6.07721735e-02, 1.19565217e-01,
       1.58695652e-01, 1.97826087e-01, 2.36956522e-01, 2.76086957e-01,
       3.15217391e-01, 3.54347826e-01, 3.93478261e-01, 4.32608696e-01,
       4.71739130e-01, 5.10869565e-01, 5.50000000e-01, 5.89130435e-01,
       6.28260870e-01, 6.67391304e-01, 7.06521739e-01, 7.45652174e-01,
       7.84782609e-01, 8.23913043e-01, 8.63043478e-01, 9.02173913e-01,
       9.41304348e-01, 9.80434783e-01])

In [25]:
m.df_rho_ary

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.01995565])

In [28]:
np.dot(m.df_rho_ary, m.f_ary)

1.0

In [ ]:
# previous
ll_new()

Array([-2.34757472, -2.19891527, -2.35438815, ..., -2.20243826,
       -2.21589033, -2.47552692], dtype=float64)

In [26]:
# now
ll_new()

Array([-2.34757305, -2.1989154 , -2.35438931, ..., -2.20243678,
       -2.21588883, -2.47552885], dtype=float64)

In [29]:
m.df_rho_ary[0] = 123
m.df_rho_ary

array([123.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   1.01995565])

In [33]:
# now again
ll_new()

m.df_rho_ary[0] 123.0


Array([-2.34757305, -2.1989154 , -2.35438931, ..., -2.20243678,
       -2.21588883, -2.47552885], dtype=float64)

# 1. Remove div from likelihood

In [5]:
def ll_new(data=data_in):
    mu = jnp.zeros_like(data)

    # poissonian
    S_pib = 5.
    S_ics = 4.
    S_bub = 3.
    S_nfw = 2.
    S_dsk = 1.

    nm = m.normalization_mask
    mu += S_pib * m.pib[0] / jnp.mean(m.pib[0][~nm])
    mu += S_ics * m.ics[0] / jnp.mean(m.ics[0][~nm])
    mu += S_bub * m.temp_bub / jnp.mean(m.temp_bub[~nm])
    mu += S_dsk * m.temp_p_dsk_fixed / jnp.mean(m.temp_p_dsk_fixed[~nm])
    mu += S_nfw * m.temp_p_nfw_fixed / jnp.mean(m.temp_p_nfw_fixed[~nm])

    # non-poissonian
    temp_ps_nfw = m.temp_ps_nfw_fixed[~m.mask_roi] / jnp.mean(m.temp_ps_nfw_fixed[~nm])
    temp_ps_dsk = m.temp_p_dsk_fixed[~m.mask_roi] / jnp.mean(m.temp_p_dsk_fixed[~nm]) # same template as poissonian
    npt_compressed = jnp.array([temp_ps_nfw, temp_ps_dsk])

    theta = []
    for ps in ["nfw", "dsk"]:
        Sps = 3.
        n1 = 5.
        n2 = 1.
        n3 = -5.5
        sb1 = 10.
        lambda_s = 0.6

        theta_tmp = jnp.array([1., n1, n2, n3, sb1, lambda_s * sb1])
        s_ary = jnp.logspace(-1., 2., 1000)
        dnds_ary = dnds(s_ary, theta_tmp)
        num_photon_for_unit_theta0 = jnp.trapz(s_ary * dnds_ary, s_ary)
        theta.append([Sps / num_photon_for_unit_theta0, n1, n2, n3, sb1, lambda_s * sb1])
    theta = jnp.array(theta)
    
    ll = log_like_np_new(
        theta=theta,
        pt_sum_compressed=mu[~m.mask_roi],
        npt_compressed=npt_compressed,
        data=data[~m.mask_roi],
        f_ary=m.f_ary,
        df_rho_ary=m.df_rho_ary,
        k_max=m.k_max,
        npixROI=m.npixROI,
    )
    print("m.df_rho_ary[0]", m.df_rho_ary[0])
    print("m.df_rho_ary[-1]", m.df_rho_ary[-1])
    return ll

In [20]:
def ll_old(data=data_in):
    mu = jnp.zeros_like(data)

    # poissonian
    S_pib = 5.
    S_ics = 4.
    S_bub = 3.
    S_nfw = 2.
    S_dsk = 1.

    nm = m.normalization_mask
    mu += S_pib * m.pib[0] / jnp.mean(m.pib[0][~nm])
    mu += S_ics * m.ics[0] / jnp.mean(m.ics[0][~nm])
    mu += S_bub * m.temp_bub / jnp.mean(m.temp_bub[~nm])
    mu += S_dsk * m.temp_p_dsk_fixed / jnp.mean(m.temp_p_dsk_fixed[~nm])
    mu += S_nfw * m.temp_p_nfw_fixed / jnp.mean(m.temp_p_nfw_fixed[~nm])

    # non-poissonian
    temp_ps_nfw = m.temp_ps_nfw_fixed[~m.mask_roi] / jnp.mean(m.temp_ps_nfw_fixed[~nm])
    temp_ps_dsk = m.temp_p_dsk_fixed[~m.mask_roi] / jnp.mean(m.temp_p_dsk_fixed[~nm]) # same template as poissonian
    npt_compressed = jnp.array([temp_ps_nfw, temp_ps_dsk])

    theta = []
    for ps in ["nfw", "dsk"]:
        Sps = 3.
        n1 = 5.
        n2 = 1.
        n3 = -5.5
        sb1 = 10.
        lambda_s = 0.6

        theta_tmp = jnp.array([1., n1, n2, n3, sb1, lambda_s * sb1])
        s_ary = jnp.logspace(-1., 2., 1000)
        dnds_ary = dnds(s_ary, theta_tmp)
        num_photon_for_unit_theta0 = jnp.trapz(s_ary * dnds_ary, s_ary)
        theta.append([Sps / num_photon_for_unit_theta0, n1, n2, n3, sb1, lambda_s * sb1])
    theta = jnp.array(theta)

    df_rho_div_f_ary = m.df_rho_ary / m.f_ary
    
    ll = log_like_np(
        theta=theta,
        pt_sum_compressed=mu[~m.mask_roi],
        npt_compressed=npt_compressed,
        data=data[~m.mask_roi],
        f_ary=m.f_ary,
        df_rho_div_f_ary=df_rho_div_f_ary,
        k_max=m.k_max,
        npixROI=m.npixROI,
    )
    return ll

In [21]:
ll_old()

Array([-2.34757472, -2.19891527, -2.35438815, ..., -2.20243826,
       -2.21589033, -2.47552692], dtype=float64)

In [19]:
ll_new()

Array([-2.34757472, -2.19891527, -2.35438815, ..., -2.20243826,
       -2.21589033, -2.47552692], dtype=float64)

# 3. Run gc17